FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive 
# use bash not sh
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y software-properties-common
RUN apt-get install -y curl
RUN apt-get install -y default-jdk wget apt-transport-https

# install logstash
RUN wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elastic-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-8.x.list
RUN apt-get update && apt-get install -y logstash

# export alias
RUN echo 'alias logstash="/usr/share/logstash/bin/logstash"' >> ~/.bashrc

# move contents
COPY . .
