# base image into kafka 

FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive 
# use bash not sh
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y software-properties-common
RUN apt-get install -y curl

# install java
RUN apt-get install -y default-jdk

# install zookeeper & kafka
RUN curl -o kafka.tgz https://dlcdn.apache.org/kafka/3.5.0/kafka_2.13-3.5.0.tgz
RUN mkdir /opt/kafka && tar -xzf kafka.tgz -C /opt/kafka --strip-components=1
WORKDIR /opt/kafka

# copy custom configs into workdir
COPY ./config/ config/

